set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(KESTREL_DEVICE 3559A)

set(CMAKE_TARGET_ARCH aarch64)

set(_CMAKE_TOOLCHAIN_LOCATION /usr/bin)
set(_CMAKE_TOOLCHAIN_PREFIX aarch64-himix100-linux-)
set(_CMAKE_SYSROOT /opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu/libc CACHE PATH "3559A cross compilation system root")
set(CMAKE_C_COMPILER    ${_CMAKE_TOOLCHAIN_LOCATION}/${_CMAKE_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER  ${_CMAKE_TOOLCHAIN_LOCATION}/${_CMAKE_TOOLCHAIN_PREFIX}g++)

include(CMakeFindBinUtils)

set(CMAKE_SYSROOT ${_CMAKE_SYSROOT})

set(CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH} ${_CMAKE_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
