set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_TARGET_ARCH x86_64)

set(_CMAKE_TOOLCHAIN_LOCATION )
set(_CMAKE_TOOLCHAIN_PREFIX )
#set(_CMAKE_LINUX_SYSROOT /usr/ CACHE PATH "AARCH64 cross compilation system root")
set(CMAKE_C_COMPILER    gcc)
set(CMAKE_CXX_COMPILER  g++)

include(CMakeFindBinUtils)

set(CMAKE_SYSROOT ${_CMAKE_LINUX_SYSROOT})

set(CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH} ${_CMAKE_LINUX_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
